# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Anatomies of Intelligence
email: info@jonathanreus.com
description: > # this means to ignore newlines until "baseurl:"
  Following from a shared interest in livecoding and real-time algorithmic performance, Joana Chicau and Jonathan Reus begin a research project into techniques for in-situ dissections of machine learning algorithms. We seek to better understand the habitual and fixed objects of machine learning as well as their terminologies, and provide counter-techniques for conditions of emergence and movement. In our processual approach, we aim to develop an online repository of terminology and techniques for a critical examination of the “anatomy” of learning and prediction processes, data corpus and models of machine learning algorithms. And explore, through performance practice, how such a toolkit can confront the idealized bodies of artificial intelligence.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://anatomiesofintelligence.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:


collections:
  # pages:
  #   output: false # explicitly disable the pages collection from rendering
  #   layout: page
  entries:  # List of entries
    output: true
    layout: empty
    permalink: /:collection/:path
  posts:
    output: true
    layout: empty
    permalink: /:collection/:path

# Build settings
markdown: kramdown
# theme: minima
theme: jekyll-theme-minimal
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - page_template.md
  - rsync_site.sh
  - index.md.old
  - index_old.md
